service: googleai-competition

package:
  exclude:
    - ./**
  include:
    - Dockerfile

plugins:
  - serverless-offline
  - serverless-domain-manager


custom:
  customDomain:
    domainName: googeai.dev.superhifi.radio
    stage: ""
    basePath: ""
    endpointType: 'regional'
    certificateName: '*.dev.superhifi.radio'
    createRoute53Record: true
     

provider:
  name: aws
  architecture: arm64
  apiName: googleai-competition-service-${opt:stage,'dev'}
  runtime: python3.10
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-west-2'}
  timeout: 900
  logRetentionInDays: 1
  versionFunctions: true

  environment:
    AWS_LAMBDA: true
    ENV: ${self:provider.stage}
    CONTENT_PATH: /mnt/tmp/content
    XDG_CACHE_HOME: /mnt/tmp/.cache
    GRADIO_TEMP_DIR: /mnt/tmp/.cache/gradio
    GRADIO_ALLOWED_PATHS: /mnt/tmp/

  ecr:
    images:
      appimage:
        path: ./

functions:
  app:
    memorySize: 10240
    timeout: 180
    maximumEventAge: 60
    maximumRetryAttempts: 0
    image:
      name: appimage
    events:
      - http:
          private: false
          path: /
          method: GET
          cors: true
      - http:
          private: false
          path: /{proxy+}
          method: ANY
          cors: true

